selected_scheme scheme-infraonly
TEXDIR /etc/texlive
TEXMFSYSCONFIG /etc/texlive/texmf-config
TEXMFCONFIG /etc/texlive/texmf-config
TEXMFLOCAL /etc/texlive/texmf-local
TEXMFHOME /etc/texlive/texmf-home
TEXMFSYSVAR /etc/texlive/texmf-var
TEXMFVAR /etc/texlive/texmf-var
option_doc 0
option_src 0
option_autobackup 0
portable 1